import { Outfit } from 'next/font/google';
import  Provider  from './provider.js';
import {
  ClerkProvider,
} from '@clerk/nextjs'
import "./globals.css";
import { Toaster } from 'sonner';

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose any weights you want
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={outfit.className}
      >
       <Provider>
        {children}
        <Toaster/>
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
